variable "private_key_id" {}
variable "private_key" {}
variable "client_email" {}
variable "client_id" {}
variable "auth_uri" {}
variable "token_uri" {}
variable "auth_provider_x509_cert_url" {}
variable "client_x509_cert_url" {}
variable "dbt_version" {}
