name: ci_pipeline

on:
  pull_request:
    branches:
      - main

env:
    DBT_CLOUD_ACCOUNT_ID: ${{ secrets.DBT_CLOUD_ACCOUNT_ID }}
    DBT_CLOUD_TOKEN: ${{ secrets.DBT_CLOUD_TOKEN }}
    TF_VAR_private_key_id: ${{ secrets.TF_VAR_private_key_id }}
    TF_VAR_private_key: ${{ secrets.TF_VAR_private_key }}
    TF_VAR_client_email: ${{ secrets.TF_VAR_client_email }}
    TF_VAR_client_id: ${{ secrets.TF_VAR_client_id }}
    TF_VAR_auth_uri: ${{ secrets.TF_VAR_auth_uri }}
    TF_VAR_token_uri: ${{ secrets.TF_VAR_token_uri }}
    TF_VAR_auth_provider_x509_cert_url: ${{ secrets.TF_VAR_auth_provider_x509_cert_url }}
    TF_VAR_client_x509_cert_url: ${{ secrets.TF_VAR_client_x509_cert_url }}
    TF_VAR_dbt_token: ${{ secrets.TF_VAR_dbt_token }}
    TF_VAR_dbt_host_url: ${{ secrets.TF_VAR_dbt_host_url }}
    DBT_DATASET: ${{ secrets.DBT_DATASET }}
    TF_VAR_github_token: ${{ secrets.TF_VAR_github_token }}

jobs:
  ci_pipeline:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.4
          terraform_wrapper: false

      - name: Setup tfcmt
        run: |
            curl -fL -o tfcmt.tar.gz https://github.com/suzuki-shunsuke/tfcmt/releases/download/v4.9.0/tfcmt_linux_amd64.tar.gz
            tar -xzf tfcmt.tar.gz
            mv tfcmt /usr/local/bin/

      - name: Run `terraform init`
        run: terraform init

      - name: Run `terraform plan`
        run: tfcmt plan -- terraform plan
